version: '3.9'

services:
  db:
    image: postgres:15-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - my-network
    env_file:
      - ./.env

  backend:
    restart: always
    build:
      context: .
    ports:
      -  8000:8000
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    entrypoint: ./wsgi-entrypoint.sh
    networks:
      - my-network
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    restart: always
    build:
      context: ./docker/nginx/
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/html
    networks:
      - my-network
    depends_on:
      - db
      - backend

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    command: certonly --webroot --webroot-path=/var/www/html --email gulyashshsh@gmail.com --agree-tos --no-eff-email -d brooklyn.kg
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/html

volumes:
  static_volume:
  postgres_data:
  media_volume:

networks:
  my-network:
