# Generated by Django 4.1.7 on 2023-02-25 23:06

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Slider1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pic", models.ImageField(upload_to=mainapp.models.image_path)),
            ],
            options={
                "verbose_name": "Картинка для первого слайдера",
                "verbose_name_plural": "Картинки для первого слайдера",
            },
        ),
        migrations.CreateModel(
            name="Slider2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pic", models.ImageField(upload_to=mainapp.models.image_path)),
            ],
            options={
                "verbose_name": "Картинка для второго слайдера",
                "verbose_name_plural": "Картинки для второго слайдера",
            },
        ),
        migrations.CreateModel(
            name="Slider3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pic", models.ImageField(upload_to=mainapp.models.image_path)),
            ],
            options={
                "verbose_name": "Картинка для третьего слайдера",
                "verbose_name_plural": "Картинки для третьего слайдера",
            },
        ),
    ]
